name: Discord Post Notify
on:
  push:
    branches:
      - main
    paths:
      - '_posts/**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 

      - name: Get Post Info and Notify
        run: |
          NEW_POST=$(git diff --name-only HEAD^ HEAD | grep '_posts/' | head -n 1)
          
          FILENAME=$(basename "$NEW_POST" .md)
          
          SLUG=$(echo $FILENAME | cut -d'-' -f4-)
          
          FINAL_URL="https://foxkicks.github.io/posts/$SLUG/"
          
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"**New Post from FoxKicks!**\n$FINAL_URL\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
